### ISSUE TITLE
Hey Scott...

### ISSUE THREAD

**Issue by rmarmer1** [ScottDikowitz/Instashare-Native-App#2]
This isn't really an issue, I just had a question bout your app... I'm quite new to react-native but wish to set it up with a Rails backend. I was looking at your app as an example, but couldn't figure out how it hooks up with a Rails backend API or where the Rails API code is...

I'd much appreciate it If you could set me straight on that. And if it would be easier, you could contact me at rmarmer1@yahoo.com

Thanks!

**Comment by scottlazz** [comment]
Hey @rmarmer1! Sorry, just saw this now. My all of my rails code can be found here: https://github.com/ScottDikowitz/Instashare
